require_relative '../config'

class GetWaterLevel
	attr_accessor :station_id

	def initialize(station_id)
		self.station_id = station_id
	end

	def create_client
		client = Savon.client do
		
			# The WSDL document provided by the NOAA.
			wsdl "https://opendap.co-ops.nos.noaa.gov/axis/webservices/waterlevelrawsixmin/wsdl"

			# Needed because (up until now), Savon doesn't match XS types to Hash keys,
			# but defaults to convert Hash message Symbols (like :from_unit) to lowerCamelCase.
			# The service expects these to be CamelCase instead. Look at Savon's log output
			# and compare it with an example request generated by soapUI.
			convert_request_keys_to :camelcase

			# Lower timeouts so these specs don't take forever when the service is not available.
			open_timeout 30
			read_timeout 30

			# Disable logging for cleaner spec output.
			log false
		end	
		client
	end

end
